#!/usr/bin/env python3
"""
Render rules.jsonl → feedback_system_rules.md (human-readable).
Single source of truth is the JSONL; MD is generated view.
"""
import json
import sys
from pathlib import Path
from collections import OrderedDict

SRC = Path('/home/piet/.openclaw/workspace/memory/rules.jsonl') if len(sys.argv) < 2 else Path(sys.argv[1])
DST = Path('/home/piet/.openclaw/workspace/feedback_system_rules.md') if len(sys.argv) < 3 else Path(sys.argv[2])

if not SRC.exists():
    print(f'Source not found: {SRC}', file=sys.stderr)
    sys.exit(1)

rules = []
with SRC.open(encoding='utf-8') as f:
    for line in f:
        line = line.strip()
        if not line:
            continue
        rules.append(json.loads(line))

# Group by category while preserving input order
categories = OrderedDict()
for r in rules:
    cat = r.get('category', 'uncategorized')
    categories.setdefault(cat, []).append(r)

header = '''---
name: System Rules & Recurring Feedback
description: Harte Betriebsregeln, die bereits mindestens einmal gebrochen wurden und einen Incident erzeugt haben. Wiederholungsschutz.
type: feedback
source-of-truth: memory/rules.jsonl
render-script: scripts/rules-render.sh
---

# System Rules & Recurring Feedback

**Auto-generated from `memory/rules.jsonl` — do NOT edit this file directly.**
Edit the JSONL instead and run `scripts/rules-render.sh` (or restart rules-render cron) to regenerate.

**Why:** Ohne diese Datei würde jede neue Session die gleichen Fehler machen. Mit ihr verhindert sie sie.

**How to apply:** Bei jeder Aktion gegen die unten gelisteten Regeln — innehalten, Regel zitieren, nicht durchziehen.

**Stats:** {n_rules} rules across {n_cats} categories. Last regenerated from JSONL.

---

'''.format(n_rules=len(rules), n_cats=len(categories))

body_parts = [header]

for cat, cat_rules in categories.items():
    body_parts.append(f'## {cat}\n\n')
    for r in cat_rules:
        rid = r.get('id', '?')
        title = r.get('title', 'untitled')
        status = r.get('status', 'active')
        since = r.get('since', '')
        body_parts.append(f'### {rid} — {title}\n')
        meta_bits = []
        if since: meta_bits.append(f'since {since}')
        if status and status != 'active': meta_bits.append(f'status={status}')
        related = r.get('related_rules', [])
        if related: meta_bits.append(f'related: {", ".join(related)}')
        upstream = r.get('related_upstream', [])
        if upstream: meta_bits.append(f'upstream: {", ".join(sorted(set(upstream)))}')
        if meta_bits:
            body_parts.append(f'*{" • ".join(meta_bits)}*\n\n')
        # Full body (preserved from original)
        full = r.get('full_body', '').rstrip()
        if full:
            body_parts.append(full + '\n\n')
        else:
            # Fallback: reconstruct from fields
            for label, key in [('Rule', 'rule'), ('Motivation', 'motivation'), ('Live-Case', 'live_case'),
                               ('Source', 'source'), ('Fix', 'fix'), ('Prevention', 'prevention')]:
                v = r.get(key, '')
                if v:
                    body_parts.append(f'**{label}:** {v}\n\n')

output = ''.join(body_parts).rstrip() + '\n'
DST.write_text(output, encoding='utf-8')
print(f'Rendered {len(rules)} rules from {SRC} to {DST}')
print(f'Size: {DST.stat().st_size} bytes')
